algoritmo "Salario"
// Função :
// Autor :
// Data : 10/03/2023
// Seção de Declarações 
var
 salarioMensal , percentualdeReajuste , salarioAjustado :real
inicio
escreval("salario mensal")
leia(salarioMensal)
escreval("percentual de reajuste")
leia(percentualdeReajuste)
salarioAjustado<-(salarioMensal + (salarioMensal / 100 * percentualdeReajuste))
escreval("salario ajustado e : ", salarioAjustado)
// Seção de Comandos 
fimalgoritmo
