algoritmo "pares de instrucoes"
// Função :
// Autor :
// Data : 10/03/2023
// Seção de Declarações 
var
A , B , C, Aa , Bb , Cc :real
inicio
// Seção de Comandos 
A <- (4/2)+(2/4)
B <- 4/(2+2)/4e
C <- (4+2)*2-4
Aa <- 4/2+2/4
Bb <- 4/2+2/4
Cc <- 4+2*2-4

escreval("A opcao 1: ", A , "  A opcao 2: ", Aa )
escreval("B opcao 1: ", B , "  B opcao 2: ", Bb )
escreval("C opcao 1: ", C , "  C opcao 2: ", Cc )
fimalgoritmo
