algoritmo "semnome"
//Faça um algoritmo para ler 20 números e armazenar em um vetor. Após a leitura total dos 20
//números, o algoritmo deve escrever esses 20 números lidos na ordem inversa.
// Função :
// Autor :
// Data : 22/03/2023
// Seção de Declarações 
var
indice: inteiro
numeros: vetor [1..20] de inteiro
Inicio
para indice de 1 ate 20 faca
leia(numeros[indice])
fimpara
para indice de 20 ate 1 passo -1 faca
escreval(numeros[indice])
fimpara
fimalgoritmo
