algoritmo "semnome"
//Modifique o exercício anterior para aceitar somente valores maiores que 0 para N. Caso o valor
//informado (para N) não seja maior que 0, deverá ser lido um novo valor para N.
// Função :
// Autor :
// Data : 19/03/2023
// Seção de Declarações 
var
 c,n :inteiro
inicio
escreval("digite numero maior que zero")
leia (n)
se n>0 entao
para c<-1 ate n faca
escreval(n)
fimpara
fimse
fimalgoritmo
